version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: "build(deps)"
    open-pull-requests-limit: 5
    groups:
      dev-dependencies:
        dependency-type: development

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: "ci(deps)"
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - "*"
