services:
    clickhouse:
        image: clickhouse/clickhouse-server:latest
        container_name: clickhouse
        ports:
            - "8123:8123" # HTTP interface
            - "9000:9000" # Native TCP interface
        volumes:
            - clickhouse_data:/var/lib/clickhouse/
            - clickhouse_logs:/var/log/clickhouse-server/
            - ./clickhouse/config/users.d:/etc/clickhouse-server/users.d:ro
            - ./clickhouse/config/config.d:/etc/clickhouse-server/config.d:ro
        restart: unless-stopped

    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        volumes:
            - grafana_data:/var/lib/grafana:rw
            - ./grafana/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/provisioning-datasources.yaml:ro
            - ./grafana/grafana-dashboards.yaml:/etc/grafana/provisioning/dashboards/provisioning-dashboards.yaml:ro
            - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
            - ./grafana/wattnet.eu.svg:/usr/share/grafana/public/img/g8_login_dark.svg
            - ./grafana/wattnet.eu.svg:/usr/share/grafana/public/img/g8_login_light.svg
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=admin
            - GF_INSTALL_PLUGINS=grafana-clickhouse-datasource
        network_mode: host # 3000
        restart: unless-stopped

volumes:
    clickhouse_data:
    clickhouse_logs:
    grafana_data:
