[tool.poetry]
name = "wattnet-storage"
version = "1.0.0"
description = "Storage Client for wattnet"
authors = ["Jaime Iglesias Blanco <iglesias@ifca.unican.es>"]
readme = "README.md"
homepage = "https://wattnet.eu"
repository = "https://github.com/wattnet/wattnet-storage"
packages = [{ include = "wattnet" }]
include = ["config/.env.example"]

[tool.poetry.plugins."wattnet.storage.clients"]
clickhouse = "wattnet.storage.clients.plugins.clickhouse:ClickHouseClient"

[tool.poetry.dependencies]
python = ">=3.10,<3.15"
pydantic-settings = "^2.13.1"
stevedore = "^5.7.0"
requests = "^2.33.0"
clickhouse-connect = "^0.10.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
