{
 "title": "wattnet raw data",
 "tags": [
  "wattnet",
  "raw",
  "generation",
  "import",
  "export"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "zone",
    "label": "Zone",
    "query": "SELECT DISTINCT zone\nFROM wattnet.zone_generation\nORDER BY zone"
   },
   {
    "name": "production_type",
    "label": "Production Type",
    "query": "SELECT DISTINCT production_type\nFROM wattnet.zone_generation\nORDER BY production_type"
   },
   {
    "name": "import",
    "label": "Import from",
    "query": "SELECT DISTINCT \"from_zone\"\nFROM wattnet.zone_import\nWHERE zone IN (${zone:singlequote})\nORDER BY \"from_zone\""
   },
   {
    "name": "export",
    "label": "Export to",
    "query": "SELECT DISTINCT \"to_zone\"\nFROM wattnet.zone_export\nWHERE zone IN (${zone:singlequote})\nORDER BY \"to_zone\""
   },
   {
    "name": "valid",
    "label": "Valid",
    "query": "SELECT DISTINCT valid\nFROM wattnet.zone_generation\nORDER BY valid"
   },
   { "name": "zone_status", "label": "Zone Status", "query": "complete, preview, missing" },
   {
    "name": "data_state",
    "label": "Data State",
    "query": "SELECT DISTINCT data_state\nFROM wattnet.zone_generation\nORDER BY data_state"
   },
   {
    "name": "datasource",
    "label": "Datasource",
    "query": "SELECT DISTINCT datasource\nFROM wattnet.zone_generation\nORDER BY datasource"
   }
  ]
 },
 "panels": [
  { "title": "$zone", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "zone" },
  {
   "title": "Zone Generation",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "rawSql": "SELECT\n    timestamp AS time,\n    concat(production_type) AS metric,\n    value as \" \"\nFROM wattnet.zone_generation FINAL\nWHERE\n    zone IN (${zone:singlequote})\n    AND production_type IN (${production_type:singlequote})\n    AND data_state IN (${data_state:singlequote})\n    AND datasource IN (${datasource:singlequote})\n    AND valid IN (${valid:singlequote})\n    AND zone_status IN (${zone_status:singlequote})\n    AND $__timeFilter(timestamp)\nORDER BY time ASC\n"
    }
   ]
  },
  {
   "title": "Zone Load",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "rawSql": "SELECT\n    timestamp AS time,\n    concat(zone) AS metric,\n    value AS \" \"\nFROM wattnet.zone_load FINAL\nWHERE\n    zone IN (${zone:singlequote})\n    AND data_state IN (${data_state:singlequote})\n    AND datasource IN (${datasource:singlequote})\n    AND valid IN (${valid:singlequote})\n    AND zone_status IN (${zone_status:singlequote})\n    AND $__timeFilter(timestamp)\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Zone Import",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "rawSql": "SELECT\n    timestamp AS time,\n    concat(from_zone, ' → ', zone) AS metric,\n    value as \" \"\nFROM wattnet.zone_import FINAL\nWHERE\n    zone IN (${zone:singlequote})\n    AND from_zone IN (${import:singlequote})\n    AND data_state IN (${data_state:singlequote})\n    AND datasource IN (${datasource:singlequote})\n    AND valid IN (${valid:singlequote})\n    AND zone_status IN (${zone_status:singlequote})\n    AND $__timeFilter(timestamp)\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Zone Export",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "rawSql": "SELECT\n    timestamp AS time,\n    concat(zone, ' → ', \"to_zone\") AS metric,\n    value as \" \"\nFROM wattnet.zone_export FINAL\nWHERE\n    zone IN (${zone:singlequote})\n    AND \"to_zone\" IN (${export:singlequote})\n    AND data_state IN (${data_state:singlequote})\n    AND datasource IN (${datasource:singlequote})\n    AND valid IN (${valid:singlequote})\n    AND zone_status IN (${zone_status:singlequote})\n    AND $__timeFilter(timestamp)\nORDER BY time ASC"
    }
   ]
  }
 ]
}