{
 "title": "wattnet zone share",
 "tags": [
  "wattnet",
  "zone",
  "distribution",
  "percentage",
  "footprints",
  "local",
  "share",
  "flows",
  "mix",
  "composition",
  "global"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "zone",
    "label": "Zone",
    "query": {
     "query": "label_values(footprint_share,zone)"
    }
   },
   {
    "name": "footprint_type",
    "label": "Footprint Type",
    "query": {
     "query": "label_values(footprint_share,footprint_type)"
    }
   },
   {
    "name": "scope",
    "label": "Footprint Scope",
    "query": {
     "query": "label_values(footprint_share,scope)"
    }
   },
   {
    "name": "valid",
    "label": "Valid",
    "query": {
     "query": "label_values(footprint_share,valid)"
    }
   },
   {
    "name": "zone_status",
    "label": "Zone Status",
    "query": {
     "query": "label_values(footprint_share,zone_status)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$zone", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "zone" },
  {
   "title": "$zone Flow Share (Distribution Vector) (Percentage)",
   "type": "barchart",
   "gridPos": { "h": 19, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "flow_share{zone=~\"$zone\", valid=~\"$valid\", zone_status=~\"$zone_status\"}[15m] > 0",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "$zone Mix Share (Composition Vector) (Percentage)",
   "type": "barchart",
   "gridPos": { "h": 19, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "mix_share{zone=~\"$zone\", valid=~\"$valid\", zone_status=~\"$zone_status\"}[15m] > 0",
     "legendFormat": " {{source}}"
    }
   ]
  },
  {
   "title": "$zone Global $footprint_type Footprint Composition (Value)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
   "repeat": "footprint_type",
   "targets": [
    {
     "expr": "footprint_share{zone=~\"$zone\", footprint_type=~\"$footprint_type\", scope=~\"$scope\", valid=~\"$valid\", zone_status=~\"$zone_status\"}[15m] > 0",
     "legendFormat": "{{source}} → {{zone}}: {{scope}} {{footprint_type}} footprint ({{unit}})"
    }
   ]
  }
 ]
}