{
 "title": "wattnet greenscore data",
 "tags": [
  "wattnet",
  "greenscore",
  "local",
  "global"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "zone",
    "label": "Zone",
    "query": "SELECT DISTINCT zone\nFROM wattnet.local_score\nORDER BY zone"
   },
   {
    "name": "scope",
    "label": "score Scope",
    "query": "SELECT DISTINCT scope\nFROM wattnet.local_score\nORDER BY scope"
   },
   {
    "name": "valid",
    "label": "Valid",
    "query": "SELECT DISTINCT valid\nFROM wattnet.local_score\nORDER BY valid"
   },
   { "name": "zone_status", "label": "Zone Status", "query": "complete, preview, missing" }
  ]
 },
 "panels": [
  { "title": "$zone", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "zone" },
  {
   "title": "Local GreenScore ($scope scope)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n    timestamp AS time,\n    concat(zone, ' / ', scope) AS metric,\n    value as \" \"\nFROM wattnet.local_score FINAL\nWHERE\n    zone IN (${zone:singlequote})\n    AND valid IN (${valid:singlequote})\n    AND zone_status IN (${zone_status:singlequote})\n    AND scope IN (${scope:singlequote})\n    AND $__timeFilter(timestamp)\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Global GreenScore score ($scope scope)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n    timestamp AS time,\n    concat(zone, ' / ', scope) AS metric,\n    value as \" \"\nFROM wattnet.global_score FINAL\nWHERE\n    zone IN (${zone:singlequote})\n    AND valid IN (${valid:singlequote})\n    AND zone_status IN (${zone_status:singlequote})\n    AND scope IN (${scope:singlequote})\n    AND $__timeFilter(timestamp)\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Comparison GreenScore score ($scope scope)",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n    timestamp AS time,\n    concat(zone, ' / ',  scope) AS metric,\n    value as \" \"\nFROM wattnet.local_score FINAL\nWHERE\n    zone IN (${zone:singlequote})\n     AND valid IN (${valid:singlequote})\n    AND zone_status IN (${zone_status:singlequote})\n    AND scope IN (${scope:singlequote})\n    AND $__timeFilter(timestamp)\nORDER BY time ASC"
    },
    {
     "rawSql": "SELECT\n    timestamp AS time,\n    concat(zone, ' / ',  scope) AS metric,\n    value as \" \"\nFROM wattnet.global_score\nWHERE\n    zone IN (${zone:singlequote})\n    AND valid IN (${valid:singlequote})\n    AND zone_status IN (${zone_status:singlequote})\n    AND scope IN (${scope:singlequote})\n    AND $__timeFilter(timestamp)\nORDER BY time ASC"
    }
   ]
  }
 ]
}