name: Publish

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    name: Build Python package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"
          allow-prereleases: true

      - name: Install Poetry
        run: pip install poetry==2.2.1

      - name: Build
        run: poetry build

      - uses: actions/upload-artifact@v7
        with:
          name: dist
          path: dist/

  pypi:
    name: Publish to PyPI
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/wattnet-storage
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: dist
          path: dist/

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true

  sbom:
    name: Generate and attach SBOMs
    needs: [pypi]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6

      - name: Generate Python package SBOM
        uses: anchore/sbom-action@v0
        with:
          path: .
          artifact-name: sbom-python.spdx.json
          upload-release-assets: true
